server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/franquiciadb
    username: root
    password: root
  sql:
    init:
      mode: never

appDescription: "MicroServicio Franquicias"
appVersion: "1.0.0"
